src/Data/StrMap.js

Quick fix for a subtle error in the JS code...

Fix broken StrMap Functor instance

---

docs/Data/Map.md
docs/Data/StrMap.md
src/Data/Map.purs
src/Data/StrMap.purs
test/Test/Data/Map.purs
test/Test/Data/StrMap.purs

Added:
* `foldableToMap`
* `foldableToMapWith`
Other things:
* Added basic tests for new functions
* Corrected doc comments on some functions mentioning array when they meant list
* Modified Gen import in tests as there was a compiler warning about it
* Docs regenerated (were slightly out of date)
---
These okay?

Couple new foldable functions to `Data.Map`

---

src/Data/Map.purs

This PR improves the performance across the board by better optimizing the sharing on pattern matches. There were a lot of duplicate checks for things like `==` and `<=` in guards. In my tests, about a 2x speedup overall. Ideally, a smarter pattern matcher could perform these optimizations, but for now we can do it manually.

Performance improvements

---

src/Data/Map.purs

Tested with 0.7.6.1. I managed to make some minor improvements to `delete` (maybe ~10%). `insert` and `lookup` are still more than 2x faster.

Performance improvements for 0.7.6

---

src/Data/Map.purs
test/Test/Data/Map.purs

Closes #52. I needed the lookupXX functions to port some GHCJS code, and then I needed findMin/findMax to implement lookupLT/GT so I figured I'd export those as well.
All the functions also have thorough tests. I am new to PureScript so do let me know if you want any style changes or things like that :)

Add lookup{LT,LE,GT,GE}, find{Min,Max}

---

src/Data/Map.purs

add mapWithKey

---

bower.json
src/Data/Map.purs
src/Data/StrMap.purs
test/Test/Data/Map.purs
test/Test/Data/StrMap.purs

Prepare for 2.0 release

---

src/Data/StrMap.js
src/Data/StrMap.purs
test/Test/Data/Map.purs
test/Test/Data/StrMap.purs

Add StrMap.mapWithKey

---

src/Data/Map.purs

Sorry we had this erroneous constraint for the past two years. But, it's unnecessary.
Let me know if there's anything you'd like changed or anything else you'd like to see here.

Relax traversable constraint

---

src/Data/StrMap.js
src/Data/StrMap.purs
test/Test/Data/StrMap.purs

Seems to have been fixed several times before, but somehow still slipped through.
Uses the same check record updates use now.

Fix hasOwnProperty bug again and forever

---

src/Data/StrMap.purs

Make StrMap.size return an integer instead of a float

---

test/Test/Data/Map.purs

Rebased Simplify test gens

---

src/Data/Map.purs
src/Data/StrMap.purs
src/Data/StrMap/ST/Unsafe.js
src/Data/StrMap/ST/Unsafe.purs
test/Test/Data/StrMap.purs

Resolves #89, resolves #36, adds `Eq1` / `Ord1` instances

Misc updates

---

src/Data/Map.purs

In the spirit of https://github.com/purescript/purescript-maps/pull/103

simplify pop code

---

src/Data/StrMap.purs
test/Test/Data/StrMap.purs

supersedes https://github.com/purescript/purescript-maps/pull/80
Rebases and implements the suggestions in that PR.

filterValues and filterKeys

---

src/Data/Map.purs

in the spirit of https://github.com/purescript/purescript-maps/pull/103

simplify insertion code

---

src/Data/Map.purs
test/Test/Data/Map.purs

Similar to https://github.com/purescript/purescript-maps/pull/97 but for the persistent `Map` data type.

persistent map filters and isSubMap

---

bench/Bench/Data/Map.purs
bench/Bench/Data/StrMap.purs
bench/Bench/Main.purs
src/Data/StrMap.purs

with benchmarks that reflect no performance degradation
addresses #108

stack-safe fromFoldable

---

src/Data/Map.purs
test/Test/Data/Map.purs

Addresses #71 and #113.
/cc @mtolly can you check whether this works for you? I don't think we need both an ascending and descending version because you can use [Data.Monoid.Dual](https://pursuit.purescript.org/packages/purescript-monoid/3.0.0/docs/Data.Monoid.Dual) if you want it in the other direction.

Add `foldSubmap` and `submap`

---

bower.json

Use foldable-traversable^3.4.0

---

src/Data/Map.purs

Make findMin and findMax tail-recursive
